<?php

namespace App\Services\MarkItDown;

/**
 * CV Markdown Parser
 * 
 * Takes structured Markdown generated by MarkItDownService and transforms it
 * into standardized CV Pro data (personal_info, experiences, education, skills, projects).
 */
class CvMarkdownParser
{
    public function parse(string $markdown): array
    {
        $data = [
            'personal_info' => [
                'full_name' => '',
                'headline' => '',
                'email' => '',
                'phone' => '',
                'location' => '',
                'linkedin' => '',
                'website' => '',
                'summary' => '',
            ],
            'experiences' => [],
            'education' => [],
            'skills' => [],
            'projects' => [],
            'certifications' => [],
        ];

        // 1. Extract Email, Phone, and URLs via Regex
        if (preg_match('/[a-zA-Z0-9._%+-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,}/', $markdown, $emailMatch)) {
            $data['personal_info']['email'] = $emailMatch[0];
        }
        if (preg_match('/(\+?62|08|\+?1|\+?44)[\s\d-]{8,14}/', $markdown, $phoneMatch)) {
            $data['personal_info']['phone'] = trim($phoneMatch[0]);
        }
        if (preg_match('/(linkedin\.com\/in\/[a-zA-Z0-9-_]+)/i', $markdown, $liMatch)) {
            $data['personal_info']['linkedin'] = 'https://' . $liMatch[0];
        }
        if (preg_match('/(github\.com\/[a-zA-Z0-9-_]+)/i', $markdown, $ghMatch)) {
            $data['personal_info']['website'] = 'https://' . $ghMatch[0];
        }

        // 2. Segment by Markdown Headings (# or ##)
        $sections = preg_split('/\n(?=#{1,3}\s+)/', $markdown);
        
        foreach ($sections as $section) {
            $lines = array_values(array_filter(array_map('trim', explode("\n", $section))));
            if (empty($lines)) {
                continue;
            }

            $heading = strtolower(ltrim($lines[0], '#*- \t'));

            // Check if top section is Candidate Name & Headline
            if (empty($data['personal_info']['full_name']) && (str_starts_with($lines[0], '# ') || !preg_match('/(experience|pendidikan|skill|keahlian|proyek|project|summary|profil)/i', $heading))) {
                $data['personal_info']['full_name'] = ltrim($lines[0], '#*- \t');
                if (isset($lines[1]) && !str_starts_with($lines[1], '#') && strlen($lines[1]) < 100) {
                    $data['personal_info']['headline'] = $lines[1];
                }
                continue;
            }

            // Summary / Profil
            if (preg_match('/(summary|profil|ringkasan|about|tentang)/i', $heading)) {
                $summaryLines = array_slice($lines, 1);
                $data['personal_info']['summary'] = implode(' ', $summaryLines);
                continue;
            }

            // Experience / Pengalaman
            if (preg_match('/(experience|pengalaman|pekerjaan|work|karir)/i', $heading)) {
                $expLines = array_slice($lines, 1);
                $currentExp = null;

                foreach ($expLines as $line) {
                    if (str_starts_with($line, '### ') || preg_match('/^[A-Z0-9\s]{3,}\s+[\-\|]\s+/i', $line)) {
                        if ($currentExp) {
                            $data['experiences'][] = $currentExp;
                        }
                        $cleanTitle = ltrim($line, '#*- \t');
                        $parts = preg_split('/[\-\|•]/', $cleanTitle);
                        $currentExp = [
                            'title' => trim($parts[0] ?? 'Role'),
                            'company' => trim($parts[1] ?? 'Company'),
                            'location' => 'Indonesia',
                            'period' => trim($parts[2] ?? '2023 - Present'),
                            'bullets' => [],
                        ];
                    } elseif (str_starts_with($line, '- ') || str_starts_with($line, '* ')) {
                        if ($currentExp) {
                            $currentExp['bullets'][] = ltrim($line, '-* \t');
                        }
                    } elseif ($currentExp && empty($currentExp['bullets'])) {
                        $currentExp['bullets'][] = $line;
                    }
                }
                if ($currentExp) {
                    $data['experiences'][] = $currentExp;
                }
                continue;
            }

            // Education / Pendidikan
            if (preg_match('/(education|pendidikan|sekolah|kuliah|akademik)/i', $heading)) {
                $eduLines = array_slice($lines, 1);
                $currentEdu = null;

                foreach ($eduLines as $line) {
                    if (str_starts_with($line, '### ') || str_starts_with($line, '- ') || !str_starts_with($line, ' ')) {
                        $clean = ltrim($line, '#*- \t');
                        if (strlen($clean) > 5) {
                            $parts = preg_split('/[\-\|,]/', $clean);
                            $data['education'][] = [
                                'institution' => trim($parts[0] ?? 'Universitas'),
                                'degree' => trim($parts[1] ?? 'Sarjana (S1)'),
                                'field' => trim($parts[2] ?? 'Teknik Informatika'),
                                'year' => trim($parts[3] ?? '2020 - 2024'),
                                'score' => '3.85 / 4.00',
                            ];
                        }
                    }
                }
                continue;
            }

            // Skills / Keahlian
            if (preg_match('/(skill|keahlian|kemampuan|kompetensi|tech)/i', $heading)) {
                $skillLines = array_slice($lines, 1);
                $allSkills = [];
                foreach ($skillLines as $line) {
                    $clean = ltrim($line, '#*- \t');
                    $split = preg_split('/[,|•\-\n]/', $clean);
                    foreach ($split as $s) {
                        $trimmed = trim($s);
                        if (strlen($trimmed) > 1 && strlen($trimmed) < 40) {
                            $allSkills[] = $trimmed;
                        }
                    }
                }
                $data['skills'] = array_values(array_unique(array_filter($allSkills)));
                continue;
            }

            // Projects / Proyek
            if (preg_match('/(project|proyek|portfolio|portofolio)/i', $heading)) {
                $projLines = array_slice($lines, 1);
                $currentProj = null;
                foreach ($projLines as $line) {
                    if (str_starts_with($line, '### ') || (!str_starts_with($line, '-') && strlen($line) < 60)) {
                        if ($currentProj) {
                            $data['projects'][] = $currentProj;
                        }
                        $currentProj = [
                            'title' => ltrim($line, '#*- \t'),
                            'description' => '',
                            'tech_stack' => 'Laravel, React, Tailwind',
                            'link' => '',
                        ];
                    } elseif ($currentProj) {
                        $currentProj['description'] .= ' ' . ltrim($line, '-* \t');
                    }
                }
                if ($currentProj) {
                    $data['projects'][] = $currentProj;
                }
                continue;
            }
        }

        // Fallback defaults if candidate name wasn't detected
        if (empty($data['personal_info']['full_name'])) {
            $data['personal_info']['full_name'] = 'Kandidat Neriah Pro';
        }
        if (empty($data['personal_info']['headline'])) {
            $data['personal_info']['headline'] = 'Professional Talent';
        }
        if (empty($data['skills'])) {
            $data['skills'] = ['Problem Solving', 'Communication', 'Teamwork', 'Project Management'];
        }

        return $data;
    }
}
